# MA + RSI Trading Strategy Configuration
# Momentum-based breakout strategy for connectivity testing

strategy:
  # Mode: 'trial' (prints signals only) or 'live' (executes real orders)
  # IMPORTANT: Start with 'trial' to test connectivity without risk
  mode: trial
  
  # List of stocks to trade
  # Add or remove stocks as needed
  # Note: Can buy multiple stocks simultaneously
  stocks:
    - TATAINV
    - GODREJPROP
  
  # Technical Indicator Parameters
  indicators:
    # Moving Average periods (in days)
    ma_short: 18          # Short-term MA (faster)
    ma_long: 36          # Long-term MA (slower)
    
    # RSI (Relative Strength Index) settings
    rsi_period: 14       # Standard RSI period (14 days)
    rsi_overbought: 70   # Overbought threshold (entry trigger)
    rsi_oversold: 30     # Oversold threshold (not used in current logic)
  
  # Trading Parameters
  trading:
    quantity: 10         # Fixed quantity per trade
    exchange: NSE        # Exchange code (NSE, BSE, etc.)
    product: cash        # Product type (cash, margin, etc.)
    order_type: market   # Order type (market or limit)
  
  # Historical Data Settings
  data:
    days_to_fetch: 30    # Number of days of historical data
    interval: 5minute       # Candle interval (1day, 1minute, 5minute, etc.)
    cache_enabled: true  # Enable local CSV caching
    cache_directory: data # Directory to store cached data

# ============================================================================
# STRATEGY LOGIC - Momentum Breakout (Long Only)
# ============================================================================
#
# LONG ENTRY (BUY) - All conditions must be true:
#   1. Short MA > Long MA (uptrend confirmed)
#   2. Previous RSI < rsi_overbought (e.g., < 70)
#   3. Current RSI >= rsi_overbought (e.g., >= 70)
#   → "Buy the breakout" - momentum accelerating into overbought zone
#
# LONG EXIT (SELL) - Any one condition triggers exit:
#   1. Short MA < Long MA (trend reversal/bearish crossover)
#   2. (Previous RSI > 50) AND (Current RSI < 50) (momentum weakening)
#   3. Current Close < Long MA (support broken)
#   → Multiple safety nets for early exit
#
# POSITION TRACKING:
#   - Only BUY if not already in position
#   - Only SELL if currently in position
#   - Can hold multiple stocks simultaneously
#
# HOLD:
#   - No clear entry/exit signal
# ============================================================================

