# MA + RSI Trading Strategy Configuration
# Momentum-based breakout strategy for connectivity testing

strategy:
  # Mode: 'trial' (prints signals only) or 'live' (executes real orders)
  # IMPORTANT: Start with 'trial' to test connectivity without risk
  mode: trial
  
  # List of stocks to trade
  # Add or remove stocks as needed
  # Note: Can buy multiple stocks simultaneously
  stocks:
    - TATINV
    - GODPRO
  
  # Technical Indicator Parameters
  indicators:
    # Moving Average periods (in days)
    ma_short: 18          # Short-term MA (faster)
    ma_long: 36          # Long-term MA (slower)
    
    # RSI (Relative Strength Index) settings
    rsi_period: 14       # Standard RSI period (14 days)
    
    # LONG position thresholds
    rsi_long_entry: 70   # RSI crosses above this = LONG entry (momentum breakout)
    
    # SHORT position thresholds
    rsi_short_entry: 40  # RSI crosses below this = SHORT entry (momentum breakdown)
    rsi_short_exit: 60   # RSI crosses above this = SHORT exit (momentum recovery)
  
  # Trading Parameters
  trading:
    quantity: 10         # Fixed quantity per trade
    exchange: NSE        # Exchange code (NSE, BSE, etc.)
    product: cash        # Product type (cash, margin, etc.)
    order_type: market   # Order type (market or limit)
  
  # Historical Data Settings
  data:
    days_to_fetch: 30    # Number of days of historical data
    interval: 5minute       # Candle interval (1day, 1minute, 5minute, etc.)
    cache_enabled: true  # Enable local CSV caching
    cache_directory: data # Directory to store cached data

# ============================================================================
# STRATEGY LOGIC - Momentum Breakout/Breakdown (Long & Short)
# ============================================================================
#
# LONG ENTRY (BUY) - All conditions must be true:
#   1. Short MA > Long MA (uptrend confirmed)
#   2. Previous RSI < rsi_long_entry (e.g., < 70)
#   3. Current RSI >= rsi_long_entry (e.g., >= 70)
#   → "Buy the breakout" - momentum accelerating into overbought zone
#
# LONG EXIT (SELL) - Any one condition triggers exit:
#   1. Short MA < Long MA (trend reversal/bearish crossover)
#   2. (Previous RSI > 50) AND (Current RSI < 50) (momentum weakening)
#   3. Current Close < Long MA (support broken)
#   → Multiple safety nets for early exit
#
# SHORT ENTRY (SHORT SELL) - All conditions must be true:
#   1. Short MA < Long MA (downtrend confirmed)
#   2. Previous RSI > rsi_short_entry (e.g., > 40)
#   3. Current RSI < rsi_short_entry (e.g., < 40)
#   → "Sell the breakdown" - momentum breaking down below 40
#
# SHORT EXIT (BUY TO COVER) - Any one condition triggers exit:
#   1. Short MA > Long MA (trend reversal/bullish crossover)
#   2. (Previous RSI < rsi_short_exit) AND (Current RSI > rsi_short_exit) (momentum recovering)
#   3. Current Close > Long MA (resistance broken)
#   → Multiple safety nets for covering shorts
#
# POSITION TRACKING:
#   - Only enter LONG if not in any position
#   - Only enter SHORT if not in any position
#   - Only exit if currently in that position type
#   - Can hold multiple stocks simultaneously (each can be LONG or SHORT)
#
# HOLD:
#   - No clear entry/exit signal
# ============================================================================

